### ISSUE TITLE
Angular 6 support?

### ISSUE THREAD

**Issue by Cero01** [irossimoline/angular4-material-table#13]
Hello,

Does this one work on Angular v6? Thanks!

**Comment by irossimoline** [comment]
Hi @Cero01, it has not been updated yet, but it just requires to update dependencies, the code itself is fully compatible.

Let me do it and I'll ping you back when done.

**Comment by irossimoline** [comment]
@Cero01, I've published a new version using angular 6 dependencies.

Please try:
`npm install angular4-material-table@0.6.0`

Please give me some feedback if you have any issues using it.

**Comment by coverbeck** [comment]
@irossimoline I'm trying to use it with Angular 6.

Do you have an example that runs? The Plunker link from your README seems to have things that are no longer present in Angular 6 (Plunker doesn't work at all for Angular, so I've tried recreating it in StackBlitz):

* MATERIAL_COMPATIBILITY_MODE
* floatPlaceholder attribute of mat-form-field
* Still running into an error with `Can't bind to 'formControl' since it isn't a known property of 'input'. `
The first two I have got around; the second one I'm looking into. I'm more familiar with AngularJS than Angular, so I'm probably missing something obvious. But if you had sample code that worked already, that would be great.

Thanks!

Charles

**Comment by irossimoline** [comment]
Hi @coverbeck,

I have created a stackblitz with the sample code. [You can check it here].(https://stackblitz.com/edit/angular-tj9f6y)

Please let me know if you have any doubt.

Regards

**Comment by irossimoline** [comment]
Regarding the other question:
- MATERIAL_COMPATIBILITY_MODE was a setting for a transition between Angular 4 and 5, but is not longer needed.
- floatPlaceholder was renamed to floatLabel in Angular 6, so it's just a rename.
- The last one is probably because you are missing the ReactiveFormsModule. [https://github.com/irossimoline/angular4-material-table/issues/12](Also you can check here for more info).

**Comment by irossimoline** [comment]
Regarding the other question:
- MATERIAL_COMPATIBILITY_MODE was a setting for a transition between Angular 4 and 5, but is not longer needed.
- floatPlaceholder was renamed to floatLabel in Angular 6, so it's just a rename.
- The last one is probably because you are missing the ReactiveFormsModule. [You can check it here](https://github.com/irossimoline/angular4-material-table/issues/12).

**Comment by coverbeck** [comment]
Hi @irossimoline -- Thanks! I will try it out in my app.

Charles

**Comment by irossimoline** [comment]
Great @coverbeck!

@Cero01, I'm going to close this issue because the tables are already working for Angular 6.

If you encounter any issue please open a new one.
